package nl.utwente.apollo

enum class Metrics {
    DRAWING_USED,
    DRAWING_ADVANCED,
    DRAWING_UNCOVERED,
    DRAWING_RAW_COVERED_COUNT,
    DRAWING_RAW_ADVANCED_COUNT,
    DRAWING_RAW_UNCOVERED_COUNT,

    LOOP_VARIETY,
    LOOP_SITUATION_VARIETY,
    LOOP_ASSESSMENT,
    LOOP_RAW_TYPE_COUNT,
    LOOP_RAW_SITUATION_COUNT,

    OO_CLASS_COUNT,
    OO_SMELLS,
    OO_RAW_CLASS_COUNT,
    OO_RAW_SMELL_COUNT,

    MESSAGEPASSING_RATIO,
    MESSAGEPASSING_RAW_GLOBAL_COUNT,
    MESSAGEPASSING_RAW_PARAMETER_COUNT
}